name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  merge_group:

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  # Functions need to be buildable without any dev dependencies and outside of
  # the context of the npm workspace because this is how Firebase will build
  # them at publish time.
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - firestore-audit-document
          - firestore-audit-log
          - firestore-redact-text
          - storage-file-intel
    defaults:
      run:
        working-directory: ./${{ matrix.function }}/functions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci --omit=dev --no-workspaces

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

  readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Generate readmes
        run: npm run generate-readmes

      - name: Check that READMEs are up to date
        run: |
          changed_files=$(git status -s -- '**/README.md' | cut -c4-)
          if [[ -n "$changed_files" ]]; then
            echo "Changes detected in `README.md` files:"
            echo "$changed_files"
            echo "Run `npm run generate-readmes` to update them."
            exit 1
          fi
